#!/usr/bin/env bash

# LinkVault Complete File Structure
# Generated for quick reference

echo "=== LinkVault Project Structure ==="
echo ""
echo "LinkVault/ (Root Directory)"
echo "│"
echo "├── Backend Files"
echo "│   ├── backend/"
echo "│   │   ├── models/"
echo "│   │   │   └── Share.js                 (MongoDB schema)"
echo "│   │   ├── routes/"
echo "│   │   │   └── shares.js                (API endpoints)"
echo "│   │   ├── config/"
echo "│   │   │   └── db.js                    (DB connection)"
echo "│   │   ├── utils/"
echo "│   │   │   └── helpers.js               (Utilities)"
echo "│   │   ├── server.js                    (Main backend entry)"
echo "│   │   ├── package.json                 (Dependencies)"
echo "│   │   ├── .env.example                 (Config template)"
echo "│   │   ├── .gitignore                   (Git ignore rules)"
echo "│   │   ├── .dockerignore                (Docker ignore rules)"
echo "│   │   └── Dockerfile                   (Container image)"
echo "│"
echo "├── Frontend Files"
echo "│   ├── frontend/"
echo "│   │   ├── src/"
echo "│   │   │   ├── pages/"
echo "│   │   │   │   ├── HomePage.jsx         (Upload page)"
echo "│   │   │   │   └── SharePage.jsx        (View page)"
echo "│   │   │   ├── components/"
echo "│   │   │   │   ├── Navigation.jsx       (Header nav)"
echo "│   │   │   │   ├── UploadForm.jsx       (Upload form)"
echo "│   │   │   │   ├── SuccessModal.jsx     (Success popup)"
echo "│   │   │   │   ├── PasswordPrompt.jsx   (Password input)"
echo "│   │   │   │   ├── TextDisplay.jsx      (Text viewer)"
echo "│   │   │   │   └── FileDisplay.jsx      (File viewer)"
echo "│   │   │   ├── App.jsx                  (Root component)"
echo "│   │   │   ├── api.js                   (API client)"
echo "│   │   │   ├── main.jsx                 (Entry point)"
echo "│   │   │   └── index.css                (Global styles)"
echo "│   │   ├── index.html                   (HTML template)"
echo "│   │   ├── vite.config.js               (Vite config)"
echo "│   │   ├── tailwind.config.js           (Tailwind config)"
echo "│   │   ├── postcss.config.js            (PostCSS config)"
echo "│   │   ├── nginx.conf                   (Web server config)"
echo "│   │   ├── package.json                 (Dependencies)"
echo "│   │   ├── .env.example                 (Config template)"
echo "│   │   ├── .gitignore                   (Git ignore rules)"
echo "│   │   ├── .eslintignore                (ESLint config)"
echo "│   │   ├── .dockerignore                (Docker ignore rules)"
echo "│   │   └── Dockerfile                   (Container image)"
echo "│"
echo "├── Documentation Files"
echo "│   ├── README.md                        (Main documentation)"
echo "│   ├── QUICKSTART.md                    (5-minute setup)"
echo "│   ├── DEPLOYMENT.md                    (Deployment guide)"
echo "│   ├── ARCHITECTURE.md                  (System design)"
echo "│   └── PROJECT_SUMMARY.md               (Project overview)"
echo "│"
echo "├── Configuration Files"
echo "│   ├── docker-compose.yml               (Multi-container setup)"
echo "│   └── .gitignore                       (Root git ignore)"
echo ""
echo "=== File Count ==="
echo "Backend Files:     11"
echo "Frontend Files:    17"
echo "Documentation:     5"
echo "Config Files:      3"
echo "Total Files:       36+"
echo ""
echo "=== Key Statistics ==="
echo "Lines of Code (Backend):    ~300 lines"
echo "Lines of Code (Frontend):   ~800 lines"
echo "Documentation Lines:        ~800 lines"
echo "API Endpoints:              5"
echo "React Components:           7"
echo "Database Schemas:           1 (Share)"
echo ""
echo "=== Technologies Used ==="
echo "Backend:  Node.js, Express.js, MongoDB, Mongoose"
echo "Frontend: React, Vite, Tailwind CSS, Axios"
echo "DevOps:   Docker, Docker Compose, Nginx"
echo ""
